obj-y 	:= core.o irq.o time.o clock.o gpio.o wdt_reset.o mv88de31xx_android.o

obj-$(CONFIG_BERLIN2CD) += berlin2cd-dt.o
obj-$(CONFIG_BERLIN_SHM) += modules/shm/
obj-$(CONFIG_BERLIN_CC) += modules/cc/
obj-$(CONFIG_BERLIN_GPIO) += modules/gpio/
obj-$(CONFIG_BERLIN_PWM) += modules/pwm/
obj-$(CONFIG_BERLIN_I2C) += modules/i2c/
obj-$(CONFIG_BERLIN_PXA3XX_NFC) += modules/nfc/
obj-$(CONFIG_BERLIN_SDIO_WLAN_8787) += modules/wlan_sd8787/
#obj-$(CONFIG_BERLIN_PE) += modules/amp/
#obj-$(CONFIG_BERLIN_FASTLOGO) += modules/fastlogo/
obj-$(CONFIG_BERLIN_GPU) += modules/gpu/
obj-$(CONFIG_BERLIN_GPU3D) += modules/gpu3D/
obj-$(CONFIG_BERLIN_PE) += modules/pe/
obj-$(CONFIG_BERLIN_FASTLOGO) += modules/fastlogo/
