# Berlin Platform Support
snd-soc-berlin-pcm-objs := pcm.o
snd-soc-berlin-dhub-objs := avio_dhub_drv.o
snd-soc-berlin-aio-objs := aio.o
snd-soc-berlin-spdif-objs := spdif.o
snd-soc-berlin-avpll-objs := avpll.o

obj-$(CONFIG_SND_SOC_BERLIN) += snd-soc-berlin-pcm.o
obj-$(CONFIG_SND_SOC_BERLIN) += snd-soc-berlin-dhub.o
obj-$(CONFIG_SND_SOC_BERLIN) += snd-soc-berlin-aio.o
obj-$(CONFIG_SND_SOC_BERLIN) += snd-soc-berlin-spdif.o
obj-$(CONFIG_SND_SOC_BERLIN) += snd-soc-berlin-avpll.o
